version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run:
          name: Publish to Gemfury
          command: |
            echo "//npm-proxy.fury.io/${GEMFURY_USER}/: authToken=${GEMFURY_AUTH_TOKEN}" > .npmrc
            npm publish
workflows:
  version: 2
  build-and-publish:
    jobs:
      - build:
          context: gemfury-upload
