version: 2

orbs:
  base: argumed/base@0.1.0
  node: argumed/node@0.1.0
  release: argumed/release@0.1.1

aliases:
  - &dockerhub_auth
    auth:
      username: $DOCKERHUB_USER
      password: $DOCKERHUB_ACCESS_TOKEN

jobs:
  build_and_test:
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            npm ci
      - run:
          name: Build the Docker builder/base image
          command: |
            npm build
       

  deploy:
    docker:
      - image: node:8-alpine
    steps:
      - checkout
      - run:
          name: Add curl
          command: apk add --no-cache curl
      - run:
          name: Push to GemFury
          command: curl --fail -F package=@`npm pack` https://${GEMFURY_TOKEN}@push.fury.io/argumed/

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          context: gemfury-upload
          filters:
              branches:
                only: master
                
                      
executors:
  debian:
    docker:
      - image: cimg/node:16.14.2
        <<: *dockerhub_auth
