name: test

on: push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    # if: contains(github.event.head_commit.modified, 'api/')
    steps:
      - uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.x
          cache: npm
      - run: npm ci
      - run: npm run test